/*
  Romanian language fix for F1 Premium.
  This file patches the Romanian dictionary created in script.js so RO is not shown as English.
*/
(function () {
  if (typeof translations === 'undefined') return;

  translations.ro = Object.assign({}, translations.en || {}, translations.ro || {}, {
    /* Navigation */
    'nav.home': 'Acasă',
    'nav.about': 'Ce este F1 Premium?',
    'nav.how': 'Cum funcționează',
    'nav.register': 'Înregistrare',
    'nav.wallet': 'Configurare wallet',
    'nav.backoffice': 'Back Office',
    'nav.faq': 'Întrebări frecvente',
    'nav.testimonials': 'Testimoniale',
    'nav.legal': 'Aviz legal',
    'nav.contact': 'Contact',

    /* Home - hero */
    'home.hero.title': 'Impulsionează-ți creșterea digitală cu F1 Premium',
    'home.hero.subtitle': 'O platformă colaborativă care combină formarea în competențe digitale cu participarea într-un sistem descentralizat.',
    'home.hero.cta': 'Descoperă cum funcționează',
    'home.hero.whatsapp': 'Discută pe WhatsApp',

    /* Home - features */
    'home.features.title': 'Caracteristici principale',
    'home.features.feature1.title': 'Descentralizat',
    'home.features.feature1.desc': 'Bazat pe tehnologia blockchain, fără control centralizat.',
    'home.features.feature2.title': 'Transparent',
    'home.features.feature2.desc': 'Reguli și distribuție vizibile în contracte inteligente.',
    'home.features.feature3.title': 'Automat',
    'home.features.feature3.desc': 'Procese executate automat, fără intervenție manuală.',
    'home.features.feature4.title': 'Colaborativ',
    'home.features.feature4.desc': 'Valoarea se generează prin participare și sprijin reciproc.',
    'home.features.feature5.title': 'Scalabil',
    'home.features.feature5.desc': 'Rețeaua ta poate crește până la 7 niveluri, prin cicluri continue.',

    /* Home - circuits */
    'home.circuits.title': 'Circuitele Bronz, Argint și Aur',
    'home.circuits.desc': 'Sistemul este structurat în trei circuite de participare cu aceeași logică și scară diferită. Începi cu Bronz (25 USDT), evoluezi către Argint (50 USDT) și consolidezi în Aur (100 USDT). Fiecare circuit distribuie activitatea până la șapte niveluri, conform unor procente fixe.',
    'home.circuits.bronce.title': 'Bronz',
    'home.circuits.bronce.desc': 'Faza de început și învățare, cu o contribuție de 25 USDT.',
    'home.circuits.plata.title': 'Argint',
    'home.circuits.plata.desc': 'Faza de dezvoltare, cu o contribuție de 50 USDT.',
    'home.circuits.oro.title': 'Aur',
    'home.circuits.oro.desc': 'Faza de consolidare, cu o contribuție de 100 USDT.',

    /* Home - call to action */
    'home.cta.title': 'Alătură-te comunității',
    'home.cta.desc': 'Activează-ți circuitul și accesează formare, instrumente și sprijin.',
    'home.cta.button': 'Începe acum',

    /* How page */
    'how.title': 'Cum funcționează F1 Premium',
    'how.intro': 'F1 Premium se bazează pe o structură de rețea cu șapte niveluri, care multiplică conexiunile pe măsură ce participanții invită alte persoane. Fiecare utilizator ocupă o poziție în rețea, iar activitatea se distribuie conform regulilor prestabilite.',
    'how.structure.title': 'Structură pe 7 niveluri',
    'how.structure.desc': 'Fiecare circuit este organizat pe șapte niveluri cu duplicare 2x. Numărul de persoane pe nivel este 2, 4, 8, 16, 32, 64 și 128. Distribuția urmează procente fixe: 50%, 4%, 5%, 6%, 7%, 8% și 9%.',
    'how.circuits.title': 'Circuite și faze',
    'how.circuits.bronce': 'Bronz: fază de început și învățare; structura crește și înveți să gestionezi rețeaua.',
    'how.circuits.plata': 'Argint: fază de dezvoltare; structura devine mai robustă, iar participarea colectivă capătă mai multă importanță.',
    'how.circuits.oro': 'Aur: fază de consolidare; rețeaua dobândește profunzime și maturitate, iar activitatea colectivă domină sistemul.',
    'how.cycles.title': 'Cicluri de continuitate',
    'how.cycles.desc': 'Sistemul funcționează prin cicluri săptămânale de 7 zile, care permit continuitatea. Constanța este mai importantă decât intensitatea.',
    'how.automation.title': 'Automatizare și contract inteligent',
    'how.automation.desc': 'Sistemul rulează printr-un contract inteligent care înregistrează activitatea, execută regulile și menține structura. Nu creează valoare de unul singur și nu înlocuiește acțiunea umană.',
    'how.participant.title': 'Rolul participantului',
    'how.participant.desc': 'Utilizatorul are un rol activ: învață sistemul, îl aplică, îl împărtășește și îi sprijină pe ceilalți.',
    'how.plan.title': 'Plan de început',
    'how.plan.desc': 'Zilele 1–7: înțelegerea sistemului, configurarea instrumentelor și primele conexiuni. Zilele 8–21: sprijinirea primelor persoane, repetare și consolidare. După ziua 30: evaluarea activității, extinderea participării și întărirea rețelei.',

    /* Registration page */
    'register.title': 'Cum să te înregistrezi',
    'register.intro': 'Pentru a te alătura F1 Premium ai nevoie de o invitație de la sponsorul tău și de un wallet de autocustodie compatibil cu opBNB.',
    'register.step1.title': '1. Obține linkul de invitație',
    'register.step1.desc': 'Cere sponsorului tău un link unic de invitație. Acest link se deschide în DApp din SafePal sau MetaMask și te conectează la echipa lui. Copiază linkul pentru a-l folosi în wallet.',
    'register.step2.title': '2. Configurează walletul',
    'register.step2.desc': 'Descarcă aplicația SafePal sau folosește extensia. Creează un wallet și păstrează în siguranță fraza seed. Apoi adaugă rețeaua opBNB, layer 2 al BNB Chain.',
    'register.step3.title': '3. Adaugă fonduri',
    'register.step3.desc': 'Depune cel puțin 25 USDT în wallet pentru a activa F1 Bronze și o mică sumă de BNB, aproximativ 0,1 BNB, pentru taxele de gas.',
    'register.step4.title': '4. Accesează linkul',
    'register.step4.desc': 'Deschide SafePal, selectează „Explorează” și lipește linkul sponsorului în căutarea DApp. Asigură-te că rețeaua selectată este opBNB sau BNB Chain.',
    'register.step5.title': '5. Selectează rețeaua',
    'register.step5.desc': 'Când se deschide DApp, apasă „Conectează” și alege SafePal ca furnizor de wallet. Autorizează conexiunea pentru ca smart contractul să poată citi adresa ta publică.',
    'register.step6.title': '6. Conectează walletul',
    'register.step6.desc': 'Înainte de contribuție, contractul va solicita autorizarea folosirii tokenurilor USDT. Confirmă aprobarea în wallet. Această operațiune nu transferă fonduri, ci permite contractului să folosească 25 USDT în tranzacția următoare.',
    'register.step7.title': '7. Aprobă contractul',
    'register.step7.desc': 'Selectează circuitul Bronz, verifică suma de 25 USDT și adresa sponsorului. Apasă „Go!” sau „Activează” pentru a trimite contribuția. Confirmă tranzacția în wallet și așteaptă confirmarea pe blockchain.',
    'register.step8.title': '8. Verifică activarea',
    'register.step8.desc': 'După finalizarea tranzacției, interfața va evidenția circuitul Bronz. Intră în back office pentru a vedea progresul și pentru a obține linkurile tale de invitație. Acum faci parte din F1 Premium!',
    'register.remark': 'Reține că participarea este voluntară și nu există garanție de returnare. Gestionează întotdeauna cheile și fondurile cu prudență.',
    'register.step1.caption': 'Solicită sponsorului linkul de invitație și copiază-l din chat.',
    'register.step2.caption': 'Verifică dacă walletul are cel puțin 25 USDT și o mică sumă de BNB pentru comisioane.',
    'register.step3.caption': 'În aplicația SafePal apasă „Explorează” pentru a deschide căutarea de DApps.',
    'register.step4.caption': 'Lipește linkul de invitație în câmpul de căutare și apasă Enter.',
    'register.step5.caption': 'Schimbă rețeaua implicită Ethereum cu opBNB/BNB Chain pentru ca smart contractul să funcționeze.',
    'register.step6.caption': 'Apasă „Conectează” pentru a lega walletul de DApp.',
    'register.step7.caption': 'Selectează SafePal sau altă opțiune compatibilă ca furnizor de conexiune.',
    'register.step8.caption': 'Acceptă termenii și apasă „Aprobă contractul” pentru a permite contractului accesul, apoi confirmă contribuția de 25 USDT. La final, circuitul Bronz va fi activat.',

    /* Wallet setup page */
    'wallet.title': 'Configurează walletul SafePal',
    'wallet.intro': 'Înainte de a te înregistra în F1 Premium ai nevoie de un wallet de autocustodie. SafePal este opțiunea recomandată datorită suportului pentru rețeaua opBNB și ușurinței de utilizare.',
    'wallet.step1.title': '1. Descarcă și instalează SafePal',
    'wallet.step1.desc': 'Caută SafePal în App Store sau Google Play ori descarcă extensia oficială. Instalează doar din surse oficiale.',
    'wallet.step2.title': '2. Creează sau importă walletul',
    'wallet.step2.desc': 'La deschiderea SafePal, selectează „Creează wallet” pentru unul nou sau „Importă wallet” dacă ai deja unul. Notează fraza seed pe hârtie și păstreaz-o offline. Nu o împărtăși niciodată.',
    'wallet.step3.title': '3. Adaugă rețeaua opBNB',
    'wallet.step3.desc': 'În secțiunea „Networks”, adaugă opBNB, layer 2 al BNB Chain. Introdu parametrii RPC corecți pentru a putea opera cu USDT și BNB.',
    'wallet.step4.title': '4. Depune fonduri',
    'wallet.step4.desc': 'Trimite cel puțin 25 USDT către adresa ta din opBNB și o mică sumă de BNB pentru gas. Le poți cumpăra într-un exchange și transfera în wallet.',
    'wallet.step5.title': '5. Verifică soldul și securitatea',
    'wallet.step5.desc': 'Verifică dacă USDT și BNB apar în wallet. Activează parola sau amprenta și asigură-te că ai o copie sigură a frazei seed.',
    'wallet.step1.caption': 'Descarcă și instalează aplicația SafePal din magazinul oficial al dispozitivului tău.',
    'wallet.step2.caption': 'Creează un wallet nou sau importă unul existent și setează o parolă de 6 cifre. Apoi selectează copia de siguranță manuală și notează cele 12 cuvinte ale frazei seed.',
    'wallet.step3.caption': 'Adaugă rețeaua opBNB în SafePal și caută tokenurile BNB(opBNB) și USDT(opBNB) pentru a le adăuga în listă.',
    'wallet.step4.caption': 'Alimentează noua ta adresă opBNB cu USDT și BNB. Poți trimite fonduri dintr-un exchange sau din alt wallet.',
    'wallet.step5.caption': 'Verifică dacă tokenurile USDT și BNB apar în wallet și activează măsuri de securitate precum PIN sau amprentă.',

    /* Back office page */
    'backoffice.title': 'Back Office',
    'backoffice.intro': 'Biroul tău virtual este panoul din care îți gestionezi participarea, rețeaua și formarea.',
    'backoffice.feature1.title': 'Gestionarea circuitelor',
    'backoffice.feature1.desc': 'Vizualizează și activează circuitele Bronz, Argint sau Aur în funcție de progres.',
    'backoffice.feature2.title': 'Arborele rețelei',
    'backoffice.feature2.desc': 'Consultă în timp real starea nivelurilor și membrilor tăi.',
    'backoffice.feature3.title': 'Rapoarte în timp real',
    'backoffice.feature3.desc': 'Verifică activitatea, reactivările și contribuțiile în mod transparent.',
    'backoffice.feature4.title': 'Formare și instrumente',
    'backoffice.feature4.desc': 'Accesează sesiuni de formare, videoclipuri și instrumente IA pentru a crea conținut digital.',
    'backoffice.feature5.title': 'Gestionarea comisioanelor',
    'backoffice.feature5.desc': 'Revizuiește soldul în funcție de starea ta, activ sau pauză, și gestionează continuitatea.',
    'backoffice.section1.title': 'Progres și reactivare',
    'backoffice.section1.desc1': 'Back office-ul tău afișează o linie de timp cu numărătoarea inversă până la următoarea reactivare. Trebuie să reactivezi la fiecare 7 zile pentru a rămâne activ; altfel treci în starea de pauză și primești doar contribuții de la nivelul direct.',
    'backoffice.section1.desc2': 'Sistemul semiautomat rezervă o parte din contribuția ta și din contribuțiile referiților pentru reactivare. Astfel se asigură continuitatea și se evită pierderea nivelurilor.',
    'backoffice.section2.title': 'Activarea circuitelor',
    'backoffice.section2.desc1': 'Din panou poți vedea starea circuitelor Bronz, Argint și Aur. Fiecare circuit are un buton pentru „Restart” când perioada se apropie de final.',
    'backoffice.section2.desc2': 'Poți activa Argint doar după finalizarea ciclului Bronz și la fel pentru Aur. Activarea depinde de progresul tău și al sponsorului.',
    'backoffice.section3.title': 'Contul meu',
    'backoffice.section3.desc1': 'În secțiunea „Contul meu” găsești date precum numărul membrilor, contribuțiile totale, recompensele primite, linkul de sponsor și codul de invitație.',
    'backoffice.section3.desc2': 'Folosește aceste date pentru a urmări creșterea și pentru a partaja linkul cu membri noi în siguranță.',
    'backoffice.section4.title': 'Detaliul circuitului',
    'backoffice.section4.desc1': 'Detaliul circuitului afișează un tabel cu nivelurile tale, numărul de persoane pe fiecare nivel, contribuțiile totale și starea ta, activ sau pauză.',
    'backoffice.section4.desc2': 'Această vedere te ajută să identifici de la ce niveluri primești contribuții și unde poți consolida rețeaua.',
    'backoffice.section5.title': 'Meniul principal',
    'backoffice.section5.desc1': 'Meniul principal oferă acces la funcții diverse: comunitate, academie, instrumente de marketing, materiale de sprijin, suport, avize legale și walletul tău.',
    'backoffice.section5.desc2': 'Explorează fiecare secțiune pentru a valorifica la maximum resursele disponibile și pentru a-ți dezvolta proiectul personal.',

    /* FAQ page */
    'faq.title': 'Întrebări frecvente',
    'faq.q1': 'Este F1 Premium o investiție?',
    'faq.a1': 'Nu. F1 Premium este o platformă de formare și participare într-un mediu de economie colaborativă.',
    'faq.q2': 'Se câștigă bani automat?',
    'faq.a2': 'Nu. Nu există garanții de venit și nici automatism economic; rezultatele depind de activitatea ta și de comunitate.',
    'faq.q3': 'Depind de alte persoane?',
    'faq.a3': 'Experiența poate fi influențată de interacțiunea cu ceilalți, dar nu există rezultate garantate.',
    'faq.q4': 'Este obligatoriu să invit persoane?',
    'faq.a4': 'Nu este obligatoriu. Participarea este voluntară, deși invitarea altor persoane poate susține creșterea sistemului.',
    'faq.q5': 'Pot pierde contribuția?',
    'faq.a5': 'Da. Participarea nu garantează returnarea contribuției. Trebuie să accepți riscurile asociate utilizării criptomonedelor.',
    'faq.q6': 'Este F1 Premium un sistem piramidal?',
    'faq.a6': 'Nu. F1 Premium nu se definește ca sistem de investiții sau model financiar; este o comunitate de economie colaborativă, fără remunerație pentru simpla recrutare.',
    'faq.q7': 'Ce primesc când intru?',
    'faq.a7': 'Primești activare în circuit, acces la formare, sprijin și acompaniere pentru dezvoltarea brandului tău personal.',
    'faq.q8': 'De cât am nevoie pentru a începe?',
    'faq.a8': 'Bronz se activează cu 25 USDT plus gas; Argint cu 50 USDT; Aur cu 100 USDT.',
    'faq.q9': 'Ce wallet folosesc?',
    'faq.a9': 'Se recomandă SafePal, deși poți folosi și alte walleturi EVM compatibile, precum MetaMask.',
    'faq.q10': 'Am nevoie imediat de 256 de persoane?',
    'faq.a10': 'Nu. Această cifră este doar un exemplu de duplicare până la șapte niveluri. Începe prin a invita câteva persoane și crește progresiv.',
    'faq.q11': 'Ce se întâmplă dacă nu rămân activ?',
    'faq.a11': 'Treci în pauză și primești doar de la nivelul direct până când reactivezi continuitatea.',
    'faq.q12': 'Trebuie să promovez F1 Premium pe rețelele sociale?',
    'faq.a12': 'Nu este vorba despre promovarea F1 Premium ca atare; formarea se concentrează pe brandul tău personal și pe atragerea conversațiilor.',
    'faq.q13': 'Trebuie să invit două persoane în fiecare săptămână?',
    'faq.a13': 'Nu este obligatoriu să inviți două persoane săptămânal. Totuși, duplicarea 2x poate accelera creșterea; strategia depinde de obiectivele și echipa ta.',
    'faq.q14': 'Ce se întâmplă dacă invitatul meu se reactivează înaintea mea?',
    'faq.a14': 'Dacă un membru al echipei se reactivează înaintea ta, va continua să contribuie la sistem, dar contribuțiile lui vor merge către structura ascendentă activă. Pentru a primi contribuții pe toate nivelurile, reactivează-te la timp.',
    'faq.q15': 'Trebuie să plătesc 25 USDT în fiecare săptămână?',
    'faq.a15': 'Nu. Realizezi doar contribuția inițială de 25 USDT pentru activarea circuitului Bronz. Reactivările ulterioare se finanțează automat dintr-o rezervă, astfel încât nu trebuie să depui fonduri suplimentare în Bronz.',
    'faq.q16': 'Ce se întâmplă dacă invit o persoană cu multă influență?',
    'faq.a16': 'Invitarea unor lideri cu viziune poate impulsiona creșterea întregii structuri. Totuși, reactivarea lor depinde de propriul ciclu; amintește-ți să îi însoțești pentru a rămâne activi și aliniați cu scopul comunității.',
    'faq.q17': 'De ce reactivarea este semiautomată?',
    'faq.a17': 'Contractul inteligent separă o parte din contribuții pentru a reactiva circuitul fără un nou depozit. Procesul este semiautomat deoarece trebuie să aprobi tranzacția de reactivare pentru a păstra controlul walletului.',
    'faq.q18': 'Ce înseamnă depozitul de reactivare?',
    'faq.a18': 'Depozitul de reactivare este un sold acumulat folosit pentru următoarea activare. Se finanțează din jumătate din contribuția ta inițială și jumătate din contribuțiile referiților, garantând continuitatea ciclului.',

    /* Testimonials */
    'testimonials.title': 'Testimoniale',
    'testimonial1.quote': 'Rețeaua m-a ajutat să învăț despre blockchain și să-mi dezvolt brandul personal. Comunitatea este extraordinară.',
    'testimonial1.author': 'Marta P.',
    'testimonial1.role': 'Antreprenoare',
    'testimonial2.quote': 'Sprijinul și transparența sistemului m-au motivat să continui participarea în fiecare săptămână.',
    'testimonial2.author': 'Carlos G.',
    'testimonial2.role': 'Participant',
    'testimonial3.quote': 'F1 Premium m-a ajutat să intru în lumea web3. Acum înțeleg mai bine cum funcționează contractele inteligente.',
    'testimonial3.author': 'Lucía M.',
    'testimonial3.role': 'Membră',
    'testimonial4.quote': 'Datorită formării și acompaniamentului am reușit să-mi creez brandul personal și să generezez conexiuni noi.',
    'testimonial4.author': 'Daniel R.',
    'testimonial4.role': 'Creator de conținut',

    /* Legal */
    'legal.title': 'Aviz legal și condiții',
    'legal.intro': 'Acest rezumat nu înlocuiește avizul legal complet, dar reunește cele mai relevante puncte pentru utilizatori.',
    'legal.item1.title': 'Natura platformei',
    'legal.item1.desc': 'F1 Premium este o platformă digitală de economie colaborativă bazată pe tehnologia blockchain. Nu este o entitate financiară și nu oferă servicii de investiții, consultanță financiară sau gestionare de capital.',
    'legal.item2.title': 'Contribuții voluntare',
    'legal.item2.desc': 'Participarea se realizează printr-o contribuție voluntară care nu constituie investiție și nu generează drepturi economice garantate.',
    'legal.item3.title': 'Lipsa garanțiilor',
    'legal.item3.desc': 'Nu există promisiune de beneficii sau rezultate asigurate. Rezultatele depind exclusiv de activitatea individuală și de mediul colectiv.',
    'legal.item4.title': 'Utilizarea criptomonedelor',
    'legal.item4.desc': 'Sistemul operează prin criptomonede. Utilizatorii trebuie să cunoască riscurile, să accepte volatilitatea și să folosească walleturi de autocustodie. F1 Premium nu custodiază fonduri și nu poate recupera active pierdute.',
    'legal.item5.title': 'Responsabilitatea utilizatorului',
    'legal.item5.desc': 'Utilizatorul este responsabil să respecte legislația țării sale, să își declare activitățile fiscale și să folosească platforma legal și etic.',
    'legal.item6.title': 'Interdicții',
    'legal.item6.desc': 'Este interzisă promisiunea de venituri garantate, inducerea în eroare privind natura sistemului sau folosirea mesajelor înșelătoare.',
    'legal.item7.title': 'Întrebări frecvente',
    'legal.item7.desc': 'Consultă secțiunea Întrebări frecvente pentru mai multe detalii despre natura non-financiară a platformei și despre participarea ta.',
    'legal.conclusion': 'Participarea la F1 Premium implică acceptarea acestor termeni și responsabilitatea individuală asupra deciziilor tale.',

    /* About page */
    'about.title': 'Ce este F1 Premium?',
    'about.section1.title': 'Introducere',
    'about.section1.desc1': 'F1 Premium este o platformă de economie colaborativă care integrează formarea în competențe digitale și un sistem de participare descentralizat. Obiectivul său este să te ajute să înveți, să creezi și să te conectezi în noua eră digitală.',
    'about.section1.desc2': 'Nu este un produs financiar și nu oferă randamente garantate; se concentrează pe educație, schimb de cunoștințe și creștere colectivă.',
    'about.section1.fig1': 'Introducere în filosofia F1 Premium.',
    'about.section1.fig2': 'Natura sistemului: colaborare și descentralizare.',
    'about.section2.title': 'Structură și operare',
    'about.section2.desc1': 'Platforma este organizată într-o rețea de șapte niveluri cu duplicare 2x, unde fiecare participant invită alte persoane, iar activitatea se distribuie conform procentelor fixe în trei circuite: Bronz, Argint și Aur.',
    'about.section2.desc2': 'Dinamica se bazează pe cicluri săptămânale care promovează continuitatea. Fiecare circuit reprezintă o fază: învățare, dezvoltare și consolidare, cu contribuții de 25, 50 și 100 USDT.',
    'about.section2.fig1': 'Reprezentarea nivelurilor rețelei.',
    'about.section2.fig2': 'Diagramă a ciclurilor săptămânale și importanța constanței.',
    'about.section3.title': 'Valori și etică',
    'about.section3.desc1': 'F1 Premium încurajează alfabetizarea digitală, transparența și construirea brandului personal. Participanții învață să comunice și să ofere valoare fără a vinde promisiuni de câștig.',
    'about.section3.desc2': 'Comunitatea se ghidează după principii de ajutor reciproc, responsabilitate și perspectivă pe termen lung.',
    'about.section3.item1': 'Învățare continuă în web3 și blockchain.',
    'about.section3.item2': 'Autocustodie și securitate financiară.',
    'about.section3.item3': 'Comunicare onestă, fără promisiuni de investiție.',
    'about.section3.item4': 'Construirea unui brand personal autentic.',
    'about.section4.title': 'Concluzie',
    'about.section4.desc1': 'F1 Premium este un spațiu pentru a te forma, a te conecta cu persoane cu interese similare și a-ți duce prezența digitală la un nivel superior.',
    'about.section4.desc2': 'Succesul tău va depinde de angajamentul și acțiunea constantă în cadrul comunității.',

    /* How page extended content */
    'how.network.title': 'Duplicare și niveluri',
    'how.network.desc1': 'Rețeaua se extinde prin duplicare 2x: fiecare persoană invită două, apoi procesul continuă. Astfel se formează niveluri de 2, 4, 8, 16, 32, 64 și 128 de membri.',
    'how.network.desc2': 'Distribuția contribuțiilor urmează procente prestabilite care recompensează activitatea colectivă.',
    'how.network.image1.caption': 'Diagramă de duplicare pe niveluri.',
    'how.network.image2.caption': 'Vizualizare a rețelei complete în circuitul Aur.',
    'how.circuits.details.title': 'Circuitele Bronz, Argint și Aur',
    'how.circuits.details.bronce.desc': 'Bronz este faza de inițiere: te familiarizezi cu sistemul, contribui cu 25 USDT și înveți să inviți și să însoțești alte persoane.',
    'how.circuits.details.plata.desc': 'Argint este faza de dezvoltare: dublezi contribuția la 50 USDT, îți extinzi rețeaua și folosești forța colectivă pentru a-ți consolida proiectul.',
    'how.circuits.details.oro.desc': 'Aur este faza de consolidare: rețeaua atinge maturitate și profunzime cu contribuții de 100 USDT.',
    'how.cycles.details.title': 'Cicluri și reactivări',
    'how.cycles.details.desc1': 'Fiecare ciclu durează 7 zile. La finalul fiecărui ciclu trebuie să reactivezi pentru a rămâne activ; altfel treci în pauză și primești doar contribuții de la nivelul direct.',
    'how.cycles.details.desc2': 'Reactivarea garantează continuitatea și distribuția echitabilă a contribuțiilor. Constanța este esențială pentru a valorifica duplicarea.',
    'how.automation.details.title': 'Smart contract și automatizare',
    'how.automation.details.desc1': 'Platforma folosește un smart contract care înregistrează contribuțiile, alocă procentele și actualizează automat stările.',
    'how.automation.details.desc2': 'Deși contractul gestionează regulile, valoarea vine din acțiunea umană: partajare, acompaniere și formare.',
    'how.participation.details.title': 'Rolul și planul participantului',
    'how.participation.details.desc1': 'Un participant învață modelul, aplică instrumentele, îl împărtășește cu alții și oferă sprijin.',
    'how.participation.details.desc2': 'Planul propus: primele 7 zile sunt pentru studierea sistemului și configurarea walletului; între zilele 8 și 21, invită și ghidează primele contacte; după ziua 30, evaluează rezultatele, împărtășește realizările și dezvoltă-ți brandul personal.',

    /* Footer */
    'footer.text': '© 2026 F1 Premium. Toate drepturile rezervate.'
  });

  document.documentElement.lang = 'ro';

  if (typeof currentLang !== 'undefined' && currentLang === 'ro' && typeof applyTranslations === 'function') {
    applyTranslations();
  }
})();
